# 환경이름설정
spring:
  config:
    activate:
      on-profile: dev

---

# WebServer 설정 (application.yml 재정의 개념)      
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    session:
      timeout: 1800              # 단위 : 초, 30분 설정
  tomcat:
    uri-encoding: UTF-8          # Spring Default

---

# Logging 설정
logging:
  pattern:
    console: "[%d{yy-MM-dd}][%thread][%-5level]\\(%F: %method\\(\\): %L\\) : %msg%n"
#    file: "[%d{yyyy-MM-dd HH:mm:ss}][%thread][%-5level]\\(%F: %method\\(\\): %L\\) : %msg%n"
#  file:
#    name: C:/ezen-fullstack/workspace/final_project_lets/log/application-dev.log
#  logback:
#    rollingpolicy:
#      max-file-size: 1MB         #default 10M
#      max-history: 31            #default 7
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.zip
  # 패키지별 Log Level 설정
  level:
    org:
      apache:
        coyote:
          http11: info          # http 요청메시지 로그
      springframework:
        jdbc: debug              # jdbc 처리 로그
        datasource:
          DataSourceTransactionManager: debug
        transaction:
          interceptor: trace

    com:
      ezen:
        springmvc:
          domain:
            member:
              mapper: trace       # mybatis 처리 로그

---

# Spring 설정
spring:
  #Database 연결 정보 설정
  config:
    import: db-config.properties
  # Thymeleaf 설정
  thymeleaf:
    # prefix: classpath:/templates/
    # suffix: .html
    cache: false                 # Cache 사용하지 않게 설정
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  # File Upload 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  # MessageSource 설정
  messages:
    # basename: messages          # Spring Default
    basename: messages,errors

---

# MyBatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.vj.lets.domain.member.dto,
                        com.vj.lets.domain.cafe.dto,
                        com.vj.lets.domain.room.dto,
                        com.vj.lets.domain.group.dto,
                        com.vj.lets.domain.plan.dto,
                        com.vj.lets.domain.support.dto,
                        com.vj.lets.domain.reservation.dto,
                        com.vj.lets.domain.article.dto,
                        com.vj.lets.domain.review.dto,
                        com.vj.lets.domain.location.dto,
                        com.vj.lets.domain.payment.dto,
                        com.vj.lets.domain.common.web

---

# 파일업로드 경로 설정
common:
  uploadPath: C:/ezen-fullstack/workspace/final_project_lets/upload/
member:
  imageLocation: C:/ezen-fullstack/workspace/final_project_lets/src/main/resources/static/assets/upload_image/member/
  imageDBPath: /assets/upload_image/member/
cafe:
  imageLocation: C:/ezen-fullstack/workspace/final_project_lets/src/main/resources/static/assets/upload_image/cafe/
  imageDBPath: /assets/upload_image/cafe/
room:
  imageLocation: C:/ezen-fullstack/workspace/final_project_lets/src/main/resources/static/assets/upload_image/room/
  imageDBPath: /assets/upload_image/room/
group:
  imageLocation: C:/ezen-fullstack/workspace/final_project_lets/src/main/resources/static/assets/upload_image/group/
  imageDBPath: /assets/upload_image/group/
article:
  imageLocation: C:/ezen-fullstack/workspace/final_project_lets/src/main/resources/static/upload_image/article/
  imageDBPath: /assets/upload_image/article/

  # google login
  google.auth.url: https://oauth2.googleapis.com
  google.login.url: https://accounts.google.com
  google.redirect.uri: http://localhost:8080/google/login/redirect
  google.client.id: 32263468491-ka20sqkvcqukc86579f4n9a6oujf6r6k.apps.googleusercontent.com
  google.secret: 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
  google.auth.scope: profile,email,openid
  
  
  